name: CI PIPELINE
on: [push, pull_request]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup python 
        uses: actions/setup-python@4 
      - name: Run test
        run: pytest
    
